services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Emma007.
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  expenseTracker:
    container_name: expenseTracker

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8081:8080"

networks:
  db:
    driver: bridge

volumes:
  db:




