spring.application.name=expenseTracker
server.port=8081

# Database connection/Setting
spring.datasource.url=jdbc:postgresql://localhost:5432/expenseTracker
spring.datasource.username=postgres
spring.datasource.password=Emma007.
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.jpa.open-in-view=false


#spring.jpa.properties.hibernate.transaction.coordinator_class=jdbc
spring.main.allow-bean-definition-overriding=true
